### PR TITLE
Cleaning code

### PR DESCRIPTION
**Pull request by kawaMANMI**

### CODE REVIEW

**Review by brosaplanella — COMMENTED** [review]
Hi Kawa! Looks good overall, just some comments on the notebooks. Unfortunately I can't annotate them in a meaningful way so will suggest the changes here.

* [x] Remove the `examples/style_figs.py:Zone.Identifier` file (I believe it was accidentally created).
* [x] Can you add some more detail on the notebooks, and maybe split the cells so you can say what you are doing in more detail. It doesn't have to be long, just explain each step. You can take the PyBaMM Getting Started notebooks as an example: https://docs.pybamm.org/en/stable/source/examples/index.html
* [x] In `examples/capacity_fade_all_models_5cycles.ipynb` please remove the cell with the commented line only.
* [x] Adjust the format: either keep all in one line (in notebooks that doesn't get checked, I think) or break the arguments of functions in one argument per line).
* [ ] If you don't want to be typing the parameters in each notebook, you can define a function that returns a parameter and store it in another file, so you can import it from each notebook. For example, you could redefine `style_figs.py` as `utils.py` and put it there.

**Comment by kawaMANMI** [comment]
@brosaplanella, Thank you for the feedback! I have addressed all the suggestions except the last point.

**Comment by kawaMANMI** [comment]
Thank you for the feedback! I have addressed all the suggestions except the last point.

**Review by brosaplanella — APPROVED** [review]
Good job! We can leave the last point for now, as it was optional.

**Pull request merged**
